### PR TITLE
Update to WS5

### PR DESCRIPTION
**Pull request by cata**
See #2

I have replicated the change patterns found in the other conversions (such as https://github.com/dotnet-websharper/charting).
I have verified that the projects build and that nuget package generation succeeds after a clean pull.

### CODE REVIEW

**Comment by granicz** [comment]
(@Jand42 is on VAC until next week, hence the delay.)

**Comment by Jand42** [comment]
I will push a small update to sources in paket.deps, everything else looks good and builds.

**Comment by granicz** [comment]
@cata Thanks for the PR! Looks like @Jand42 released the changes a while ago, and the packages should be on NuGet now.

**Comment by cata** [comment]
@granicz @Jand42 we are already using the new packages in production, thank you for merging!

**Pull request merged**
